### ISSUE TITLE
'lambda_function': cannot import name '_rand' from 'ddtrace.internal'

### ISSUE THREAD

**Issue by bryantbiggs** [DataDog/datadog-lambda-python#88]
## Expected Behavior
Upgrading the lambda layer of `datadog-lambda` should not fail due to an import issue

## Actual Behavior

see here for full output of failure: [ref](https://github.com/DataDog/datadog-serverless-functions/pull/358/checks?check_run_id=1166174622)

if I downgrade ddtrace to before [this change](https://github.com/DataDog/dd-trace-py/pull/1474) was made in v0.40.0 it works as shown [here](https://github.com/DataDog/datadog-serverless-functions/pull/358/commits/0c4345b97f49261acdd4d260ab1d9c116ad7caa1)

## Steps to Reproduce the Problem

  1. go to https://github.com/DataDog/datadog-serverless-functions
  2. upgrade `datadog-lambda` in `setup.py` to 2.21.0
  3. build will fail integration tests with `'lambda_function': cannot import name '_rand' from 'ddtrace.internal'`
  4. you can verify where this is occurring by down-pinning the version of ddtrace to 0.39.0 as shown [here](https://github.com/DataDog/datadog-serverless-functions/pull/358/commits/0c4345b97f49261acdd4d260ab1d9c116ad7caa1) and the integration tests pass 

## Specifications

  - Datadog Lambda Layer version: 2.21.0
  - Python version: 3.7/3.8
  
## Stacktrace
  
  ```
  forwarder_1  | Lambda API listening on port 9001...
recorder_1   | Starting recorder
recorder_1   | Started recorder on port 8080
forwarder_1  | START RequestId: b6d3226d-cb61-1935-065f-765126265d0d Version: $LATEST
forwarder_1  | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
forwarder_1  | END RequestId: b6d3226d-cb61-1935-065f-765126265d0d
forwarder_1  | REPORT RequestId: b6d3226d-cb61-1935-065f-765126265d0d	Init Duration: 769.74 ms	Duration: 4.89 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 53 MB	
forwarder_1  | START RequestId: c525c53d-996d-1c2b-f66f-b6b0555d4b20 Version: $LATEST
forwarder_1  | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
forwarder_1  | END RequestId: c525c53d-996d-1c2b-f66f-b6b0555d4b20
forwarder_1  | REPORT RequestId: c525c53d-996d-1c2b-f66f-b6b0555d4b20	Duration: 3.29 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 53 MB	
forwarder_1  | START RequestId: 7558f9ac-8c11-189b-6724-3ca9bd0d8647 Version: $LATEST
forwarder_1  | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
forwarder_1  | END RequestId: 7558f9ac-8c11-189b-6724-3ca9bd0d8647
forwarder_1  | REPORT RequestId: 7558f9ac-8c11-189b-6724-3ca9bd0d8647	Duration: 3.85 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 53 MB	
forwarder_1  | START RequestId: 91fae490-9d34-1da5-2783-45d363dca3e1 Version: $LATEST
forwarder_1  | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
forwarder_1  | END RequestId: 91fae490-9d34-1da5-2783-45d363dca3e1
forwarder_1  | REPORT RequestId: 91fae490-9d34-1da5-2783-45d363dca3e1	Duration: 3.62 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 53 MB	
forwarder_1  | START RequestId: 0df42748-676b-1079-48b3-c395e284c1f2 Version: $LATEST
forwarder_1  | [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
forwarder_1  | END RequestId: 0df42748-676b-1079-48b3-c395e284c1f2
forwarder_1  | REPORT RequestId: 0df42748-676b-1079-48b3-c395e284c1f2	Duration: 3.60 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 53 MB	
tester_1     | EEEEE
tester_1     | ======================================================================
tester_1     | ERROR: test_cloudwatch_log (test_snapshots.TestForwarderSnapshots)
tester_1     | ----------------------------------------------------------------------
tester_1     | Traceback (most recent call last):
tester_1     |   File "/test_snapshots.py", line 104, in setUp
tester_1     |     recording["events"][0]["path"],
tester_1     | IndexError: list index out of range
tester_1     | 
tester_1     | ======================================================================
tester_1     | ERROR: test_cloudwatch_log_cold_start (test_snapshots.TestForwarderSnapshots)
tester_1     | ----------------------------------------------------------------------
tester_1     | Traceback (most recent call last):
tester_1     |   File "/test_snapshots.py", line 104, in setUp
tester_1     |     recording["events"][0]["path"],
tester_1     | IndexError: list index out of range
tester_1     | 
tester_1     | ======================================================================
tester_1     | ERROR: test_cloudwatch_log_custom_tags (test_snapshots.TestForwarderSnapshots)
tester_1     | ----------------------------------------------------------------------
tester_1     | Traceback (most recent call last):
tester_1     |   File "/test_snapshots.py", line 104, in setUp
tester_1     |     recording["events"][0]["path"],
tester_1     | IndexError: list index out of range
tester_1     | 
tester_1     | ======================================================================
tester_1     | ERROR: test_cloudwatch_log_lambda_invocation (test_snapshots.TestForwarderSnapshots)
tester_1     | ----------------------------------------------------------------------
tester_1     | Traceback (most recent call last):
tester_1     |   File "/test_snapshots.py", line 104, in setUp
tester_1     |     recording["events"][0]["path"],
tester_1     | IndexError: list index out of range
tester_1     | 
tester_1     | ======================================================================
tester_1     | ERROR: test_cloudwatch_log_timeout (test_snapshots.TestForwarderSnapshots)
tester_1     | ----------------------------------------------------------------------
tester_1     | Traceback (most recent call last):
tester_1     |   File "/test_snapshots.py", line 104, in setUp
tester_1     |     recording["events"][0]["path"],
tester_1     | IndexError: list index out of range
tester_1     | 
tester_1     | ----------------------------------------------------------------------
tester_1     | Ran 5 tests in 0.771s
tester_1     | 
tester_1     | FAILED (errors=5)
integration_tests_tester_1 exited with code 1
  ```

**Comment by bryantbiggs** [comment]
cc @Kyle-Verhoog

**Comment by Kyle-Verhoog** [comment]
Hi @bryantbiggs, 

Looks like you copied a successful job run but I found the failing one [here](https://github.com/DataDog/datadog-serverless-functions/runs/1166122560).

Hmm `_rand` is a c-extension module. From the logs of the job it looks like the wheel is being installed (which should have the c-extensions built already, I can see `_rand.cpython-37m-x86_64-linux-gnu.so` in the logs) and then passed into the docker container wherein it fails. The docker container seems to be based off a linux image which should be fine but the issue might be the difference in platforms of the host and the docker container.

I'm not very familiar with this setup or how this packaging works for the serverless stuff. @tianchu hopefully this context helps some 🙂

**Comment by tianchu** [comment]
Correct, the most recent version of `ddtrace` (a dependency of `datadog-lambda`) introduces 
C code, so it might be installed/compiled in Linux. See here https://docs.datadoghq.com/serverless/installation/python?tab=custom#using-the-package. We recommend you use the prebuilt [Lambda layer](https://docs.datadoghq.com/serverless/installation/python?tab=custom#using-the-layer) or build the dependencies in a container.

**Comment by bryantbiggs** [comment]
thanks for the info @tianchu - so what is the plan to update the usage of `datadog-lambda` for the forwarder functions? i.e. - https://github.com/DataDog/datadog-serverless-functions/pull/358 which is what preempted this issue

**Comment by tianchu** [comment]
Are you building the forwarder zip using this [script](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/tools/build_bundle.sh)? It builds forwarder zip in a container.

**Comment by bryantbiggs** [comment]
no no, I think you mis-understand. I'm not doing anything locally, this is updating the version of `datadog-lambda` in the `datadog-serverless-functions` repository so that the Datadog forwarders are using the latest `datadog-lambda` version. its not essential for the PR I was opening to fix some documentation so I will revert the package upgrade for now - but I guess there will need to be some action at some point if that version is ever to be updated

**Comment by tianchu** [comment]
Correct, that's why I mentioned that script, because that script installs `datadog-lambda` to the forwarder zip using a container, we can safely upgrade `datadog-lambda` to its latest version without problem. All we need to do is to bump this version number [here](https://github.com/DataDog/datadog-serverless-functions/blob/9cd75cf19b6f4b13f1e3ffba9c1452e70d91d73b/aws/logs_monitoring/setup.py#L20), and when we run the script to release the next version of forwarder, the upgraded `datadog-lambda` will be automatically installed by that script.

**Comment by bryantbiggs** [comment]
hmm, ok. I can put the version back to latest but I'm not sure how to get the integration tests to pass since it looks like the integration tests are building the bundle with that script https://github.com/DataDog/datadog-serverless-functions/blob/869305a3d5b06cf3a23f88f16eee580d526d5111/aws/logs_monitoring/tools/integration_tests/integration_tests.sh#L88

lets continue the convo over on that PR (when you get time, doesn't have to be right now) since thats where its relevant - https://github.com/DataDog/datadog-serverless-functions/pull/358

**Comment by fnote** [comment]
I have a lambda written in python. I have been trying to send some custom metrics from this lambda to datadog. but trying to do so I get the below error

[ERROR] Runtime.ImportModuleError: Unable to import module 'index': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
Traceback (most recent call last):

my requirement.txt file for the lambda is as below ,

requests==2.25.0
logging-formatter-anticrlf==1.2
pymysql==1.0.2
datadog==0.39.0
ddtrace==0.45.0
datadog-lambda==2.28.0

from my understanding, this happens due to a dependency mismatch. can someone help me with this ?

**Comment by tianchu** [comment]
@fnote https://docs.datadoghq.com/serverless/installation/python?tab=custom#using-the-package might help? `ddtrace` uses C extension, so it must be built on the same platform (Linux) that AWS Lambda runs on. Were you building your Lambda deployment package from Windows or Mac? If so, I suggest using the prebuilt Lambda layer https://docs.datadoghq.com/serverless/installation/python?tab=custom#using-the-layer, and you can safely remove 

```
datadog==0.39.0
ddtrace==0.45.0
datadog-lambda==2.28.0
```

from your requirements.txt

**Comment by NickolasHKraus** [comment]
I ran into this issue as well.

```
{
  "errorMessage": "Unable to import module 'X': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}
```

`_rand` is a Python C extension, however since the ddtrace package was installed on macOS, it was compiled against the macOS kernel (`_rand.cpython-38-darwin.so`).

Deploying to AWS Lambda via Serverless Framework on macOS was the root cause.

**Comment by aaronabf** [comment]
I ran into this issue running the Datadog Forwarder Lambda. I had to switch my Lamdba's architecture from `arm64` to `x86_64`.

**Comment by stephanfenton** [comment]
I saw these errors when upgrading the lambda function, and the datadog_python and datadog_extension layers. We use Terraform to deploy the changes. We also changed the Python version from 3.7 to 3.8.

Lambda: 3.44.0 -> 3.60.0
datadog_python: 53 -> 63
datadog_extension: 22 -> 31

**Comment by harshavardhana-reddy-alation** [comment]
I'm facing the same issue when I'm creating lamda functing terraform, Can some please help me to fix this isssue. 
error msg is:
 Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
Traceback (most recent call last)

**Comment by harshavardhana-reddy-alation** [comment]
Hi Team,

I resolved the issue by changing runtime from python3.7 to python3.8.
May I know the reason why it was not working with python 3.7?

Regards,
Harsha

**Comment by harshavardhana-reddy-alation** [comment]
And I'm not using any layers here ..is it mandatory to create layers or use
layers?
Without using layers also I'm able to see logs data dog console using lamda
S3 trigger
Regards,
Harsha

**Comment by tianchu** [comment]
It's not that layers are not required. What I meant by that was you could either install datadog-lambda-python as a prebuilt Lambda layer provided by Datadog or install datadog-lambda-python as a normal dependency using pip. https://docs.datadoghq.com/serverless/installation/python/?tab=custom (option A vs B in step 1)

**Comment by berniedurfee-renaissance** [comment]
I'm getting the same error using the [Terraform module](https://registry.terraform.io/modules/terraform-aws-modules/datadog-forwarders/aws/latest/submodules/log_forwarder) to deploy the Lambda.

**Comment by berniedurfee-renaissance** [comment]
https://github.com/terraform-aws-modules/terraform-aws-datadog-forwarders/issues/32
